Add lofreq
viash-hub/biobase pull request #17
Opened 2024-02-06 12:44 UTC by KaiWaldrant

## Description
Add `lofreq` biobase components:

* `call`
* `indelqual`

## Issue ticket number

## Checklist before requesting a review

- [x] I have performed a self-review of my code

- [x] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [x] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [x] I have tested my code with `viash ns test --parallel -q <name or namespace>`

```bash
viash ns test --parallel -q lofreq
The working directory for the namespace tests is /tmp/viash_ns_test3438401139745231693
           namespace        functionality             platform            test_name exit_code duration               result
              lofreq     lofreq_indelqual               docker                start                                        
              lofreq          lofreq_call               docker                start                                        
              lofreq          lofreq_call               docker     build_executable         0        2              SUCCESS
              lofreq          lofreq_call               docker              test.sh         0        1              SUCCESS
              lofreq     lofreq_indelqual               docker     build_executable         0        2              SUCCESS
              lofreq     lofreq_indelqual               docker              test.sh         0        2              SUCCESS
Not all configs built and tested successfully
  6 configs were disabled
  4/4 configs built and tested successfully
  ```

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [x] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

2024-02-10 08:52 UTC, rcannood requested changes
Thanks for your PR! See comments :relaxed:

2024-02-10 08:52 UTC, rcannood commented on src/lofreq/call/config.vsh.yaml
> +          example: "output.vcf"
`--out` is renamed to `--output` but `--ref` is not renamed to `--reference`.

WDYT? Should `--output` be changed back into `--out` or `--ref` to `--reference`? ^^

2024-02-10 08:52 UTC, rcannood commented on src/lofreq/call/config.vsh.yaml
> +            Limit calls to this region (chrom:start-end) [null].
Make the default values a little more explicit:

```suggestion
            Limit calls to this region (chrom:start-end). Default: none.

2024-02-10 08:52 UTC, rcannood commented on src/lofreq/call/config.vsh.yaml
> +            Skip any base with baseQ smaller than INT [6].
Make the default values a little more explicit:

```suggestion
            Skip any base with baseQ smaller than INT. Default: 6.

2024-02-10 08:52 UTC, rcannood commented on src/lofreq/indelqual/test_data/hg38_chr21.fa
How big is this file? Do you think we could find a smaller one?

2024-02-12 10:51 UTC, KaiWaldrant commented on src/lofreq/indelqual/test_data/hg38_chr21.fa
about 50 MB :s

2024-02-15 05:46 UTC, rcannood commented on src/lofreq/indelqual/test_data/hg38_chr21.fa
I'm not confortable yet adding a 50MB resource file to the repo :sweat_smile:

2024-02-15 08:58 UTC, rcannood approved these changes

2024-02-15 09:14 UTC, merged