Busco list datasets
viash-hub/biobase pull request #18
Opened 2024-02-06 15:04 UTC by dorien-er

## Description

add component to list available busco datasets (that can be used in the busco component)

## Issue ticket number

Closes #xxxx 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

- [ ] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [ ] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [ ] I have tested my code with `viash ns test --parallel -q <name or namespace>`

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

2024-02-06 16:03 UTC, dorien-er commented
this is a supporting component that's referenced in busco/busco, is it useful to add the help text here again, since they're already present in busco/busco?

2024-02-07 10:55 UTC, rcannood commented
> this is a supporting component that's referred to in busco/busco, is it useful to add the help text here again, since they're already present in busco/busco?

One possibility is to add it to one entry but structure it a little bit, e.g.

* Add busco: <description>
  - busco run (#...)
  - busco list (#...)
  - busco download (#...)

2024-02-09 15:43 UTC, dorien-er commented
> > this is a supporting component that's referred to in busco/busco, is it useful to add the help text here again, since they're already present in busco/busco?
> 
> One possibility is to add it to one entry but structure it a little bit, e.g.
> 
> * Add busco: 
>   
>   * busco run (#...)
>   * busco list (#...)
>   * busco download (#...)
> 
> WDYT?

Sounds good... But what about the help.txt file - doesn't seem useful to have that seem file in all 3 subcomponents, shall I just leave it under the main component only?

2024-02-10 09:16 UTC, rcannood approved these changes

2024-02-10 09:18 UTC, rcannood requested changes

2024-02-10 09:18 UTC, rcannood commented on CHANGELOG.md
> +    - `busco_list_datasets`: Lists available busco datasets (PR #18)
Would this make sense?

```suggestion
    - `busco/busco_run`: Assess genome assembly and annotation completeness with single copy orthologs (PR #6).
    - `busco/busco_list_datasets`: Lists available busco datasets (PR #18)

2024-02-11 14:33 UTC, rcannood approved these changes

2024-02-11 14:33 UTC, merged